import { Models3dItem } from '../entities/3d_object_model';

export const models3d: Models3dItem[] = [
  {
    id:"1",
    title: 'Diseño de Porcino',
    author: 'Oscar',
    modelPath: "/3d-objects/cerdo.glb",
    nutritionalInfo: 'Carne rica en proteínas, vitamina B6, B12 y minerales como zinc y hierro.',
    growthPeriod: '5 - 6 meses para peso de mercado (aprox. 100-110 kg).',
    waterRequirements: 'De 20 a 30 litros de agua limpia por día por animal.',
    recommendedFertilizers: 'No aplica',
    commonDiseases: 'Peste porcina, erisipela, problemas respiratorios.',
    estimatedProduction: '100 kg de carne en canal por unidad.',
    currentPrice: 4500
  },
  {
    id:"2",
    title: 'Diseño de Heno',
    author: 'Oscar',
    modelPath: "/3d-objects/heno.glb",
    nutritionalInfo: 'Alto contenido de fibra bruta, ideal para el sistema digestivo de rumiantes y equinos.',
    growthPeriod: '60 - 90 días por corte (dependiendo del tipo de pasto).',
    waterRequirements: 'Moderado (depende de la lluvia estacional o riego por aspersión).',
    recommendedFertilizers: 'Nitrógeno y Fósforo tras cada corte para estimular el rebrote.',
    commonDiseases: 'Hongos por exceso de humedad durante el almacenamiento (Moho).',
    estimatedProduction: '150 pacas por hectárea por corte.',
    currentPrice: 120
  },
  {
    id:"3",
    title: 'Diseño de Maíz',
    author: 'Joshua',
    modelPath: "/3d-objects/elote.glb",
    nutritionalInfo: 'Excelente fuente de carbohidratos, fibra, vitamina A, B y fósforo.',
    growthPeriod: '90 - 120 días hasta la cosecha.',
    waterRequirements: '500 - 800 mm distribuidos a lo largo del ciclo, crítico en la floración.',
    recommendedFertilizers: 'Fertilizantes NPK (Nitrógeno, Fósforo, Potasio) y Zinc.',
    commonDiseases: 'Gusano cogollero, roya del maíz, carbón del maíz.',
    estimatedProduction: '4.5 toneladas por hectárea.',
    currentPrice: 350
  },
  {
    id:"4",
    title: 'Diseño de Girasol',
    author: 'Oscar',
    modelPath: "/3d-objects/girasol.glb",
    nutritionalInfo: 'Semillas ricas en vitamina E, grasas saludables (Omega-6) y minerales.',
    growthPeriod: '80 - 100 días.',
    waterRequirements: 'Bajo a moderado; es una planta muy resistente a la sequía gracias a sus raíces profundas.',
    recommendedFertilizers: 'Rico en Potasio y Boro para mejorar el llenado de la semilla.',
    commonDiseases: 'Mildiu, podredumbre gris (Botrytis), mildiu polvoriento.',
    estimatedProduction: '2.2 toneladas de semilla por hectárea.',
    currentPrice: 600
  },
  {
    id:"5",
    title: 'Diseño de Macetera',
    author: 'Joshua',
    modelPath: "/3d-objects/macetera.glb",
    nutritionalInfo: 'Soporte físico contenedor de sustrato orgánico enriquecido.',
    growthPeriod: 'N/A (Ciclo continuo según el cultivo plantado).',
    waterRequirements: 'Controlado (depende directamente de la planta que aloje).',
    recommendedFertilizers: 'Abono orgánico, humus de lombriz mezclado en el sustrato.',
    commonDiseases: 'Acumulación de sales o proliferación de hongos en la raíz por mal drenaje.',
    estimatedProduction: 'Capacidad para 1 planta grande o 3 hortalizas pequeñas.',
    currentPrice: 85
  },
  {
    id:"6",
    title: 'Diseño de Arduino',
    author: 'Oscar',
    modelPath: "/3d-objects/panelSolar.glb",
    nutritionalInfo: 'Dispositivo electrónico para automatización de riego y monitoreo de sensores.',
    growthPeriod: 'Vida útil estimada de 5 a 8 años con mantenimiento adecuado.',
    waterRequirements: 'Ninguno (Mantener completamente seco y protegido de la intemperie).',
    recommendedFertilizers: 'No aplica',
    commonDiseases: 'Corrosión por humedad, sobrecalentamiento, fallos por picos de voltaje.',
    estimatedProduction: 'Monitoreo 24/7 de 4 sensores ambientales.',
    currentPrice: 1200
  },
  {
    id:"7",
    title: 'Diseño de Yuca',
    author: 'Joshua',
    modelPath: "/3d-objects/yuca.glb",
    nutritionalInfo: 'Tuberculo con alto valor energético, rico en almidón y libre de gluten.',
    growthPeriod: '8 - 12 meses para la maduración de las raíces.',
    waterRequirements: 'Moderado; muy tolerante a sequías una vez establecida.',
    recommendedFertilizers: 'Alto requerimiento de Potasio para el desarrollo de raíces tuberosas.',
    commonDiseases: 'Bacteriosis vascular de la yuca, mosca blanca, superatropamiento.',
    estimatedProduction: '12 toneladas por hectárea.',
    currentPrice: 280
  },
  {
    id:"8",
    title: 'Diseño de Ayote',
    author: 'Oscar',
    modelPath: "/3d-objects/ayote.glb",
    nutritionalInfo: 'Bajo en calorías, alto en agua, fibra, beta-carotenos y vitaminas A y C.',
    growthPeriod: '90 - 110 días.',
    waterRequirements: 'Frecuente durante las primeras etapas y el desarrollo del fruto.',
    recommendedFertilizers: 'Materia orgánica (estiércol compuesto) y fertilizantes ricos en Fósforo.',
    commonDiseases: 'Cenicilla (Oídium), virosis transmitida por áfidos, mildiú velloso.',
    estimatedProduction: '15 toneladas por hectárea.',
    currentPrice: 150
  },
  {
    id:"9",
    title: 'Diseño de Cebolla',
    author: 'Joshua',
    modelPath: "/3d-objects/cebolla.glb",
    nutritionalInfo: 'Contiene antioxidantes, compuestos azufrados saludables, potasio y vitamina C.',
    growthPeriod: '120 - 150 días desde el trasplante.',
    waterRequirements: 'Riego regular pero ligero; evitar encharcamientos para que no se pudra el bulbo.',
    recommendedFertilizers: 'Nitrógeno en las primeras fases; Azufre para acentuar el sabor y aroma.',
    commonDiseases: 'Mildiu de la cebolla, raíz rosada, trips.',
    estimatedProduction: '25 toneladas por hectárea.',
    currentPrice: 420
  },
  {
    id:"10",
    title: 'Diseño de Chiltoma',
    author: 'Oscar',
    modelPath: "/3d-objects/chiltoma.glb",
    nutritionalInfo: 'Aporte masivo de vitamina C (más que los cítricos), vitamina A y antioxidantes.',
    growthPeriod: '70 - 90 días después del trasplante.',
    waterRequirements: 'Constante y uniforme; el estrés hídrico provoca la caída de flores.',
    recommendedFertilizers: 'Equilibrio NPK, con especial énfasis en Calcio para evitar la podredumbre apical.',
    commonDiseases: 'Picudo del chile, cenicilla, marchitez por Phytophthora.',
    estimatedProduction: '18 toneladas por hectárea.',
    currentPrice: 310
  },
  {
    id:"11",
    title: 'Diseño de Tomate',
    author: 'Joshua',
    modelPath: "/3d-objects/tomate.glb",
    nutritionalInfo: 'Excelente fuente de licopeno (antioxidante clave), potasio, vitaminas C y K.',
    growthPeriod: '80 - 100 días desde el trasplante.',
    waterRequirements: 'Alto y regular; el riego por goteo es el más recomendado.',
    recommendedFertilizers: 'Fósforo al inicio, Potasio durante la fructificación y aportes de Calcio.',
    commonDiseases: 'Tizón temprano, tizón tardío, mosca blanca, virus del bronceado.',
    estimatedProduction: '30 toneladas por hectárea (en condiciones óptimas).',
    currentPrice: 490
  },
  {
    id:"12",
    title: 'Diseño de Zanahoria',
    author: 'Oscar',
    modelPath: "/3d-objects/zanahoria.glb",
    nutritionalInfo: 'Famosa por su altísimo contenido de beta-caroteno (Vitamina A), buena para la vista.',
    growthPeriod: '90 - 110 días.',
    waterRequirements: 'Humedad constante para evitar que la raíz se agriete o se bifurque.',
    recommendedFertilizers: 'Bajo en Nitrógeno (para evitar exceso de follaje) y alto en Potasio.',
    commonDiseases: 'Mosca de la zanahoria, alternaria, nematodos del suelo.',
    estimatedProduction: '20 toneladas por hectárea.',
    currentPrice: 220
  }
];